### ISSUE TITLE
You must end your route with /

### ISSUE THREAD

**Issue by wl496928838** [stonecircle/kue-ui-express#2]
How to deal with this???

```
var kue = require('kue');
var express = require('express');
var kueUiExpress = require('kue-ui-express');
var app = express();

kue.createQueue();

kueUiExpress(app, '/kue', '/api');

// Mount kue JSON api
app.use('/api', kue.app);

app.listen(3000);
```

**Comment by jhunken** [comment]
I had the same problem and changed it to `kueUIExpress(app, '/kue/', '/api/kue');` and it seems to work. Looks like the README might need to be updated.

**Comment by wl496928838** [comment]
yes update the README

**Comment by mansona** [comment]
This has been fixed in https://github.com/stonecircle/kue-ui-express/pull/3 👍 

let me know if you have any more issues
